name: Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"
          cache: pip
      - name: Install the project
        run: python -m pip install -e ".[backoffice,test]"
      - name: Run tests
        run: python -m pytest
